package:
  format-version: "1.0.0"
  name: "cec173x_soteria_lib"
  type: "application"
  status: "production"
  required: true
  version: "3.1.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.14.0"
    - name: "dev_packs"
      type: "package"
      version: "3.14.0"