package:
  format-version: "1.0.0"
  name: "cec173x_soteria_lib"
  type: "application"
  status: "production"
  required: true
  version: "3.2.1"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.16.0"
    - name: "dev_packs"
      type: "package"
      version: "3.16.0"
    - name: "pmci"
      type: "package"
      version: "3.0.0"