package:
  format-version: "1.0.0"
  name: "cec173x_soteria_lib"
  type: "application"
  status: "production"
  required: false
  version: "v3.4.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.18.0"
    - name: "pmci"
      type: "package"
      version: "v3.1.0"