
/*****************************************************************************
* Copyright (c) 2022 Microchip Technology Inc. and its subsidiaries.
* You may use this software and any derivatives exclusively with
* Microchip products.
* THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".
* NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE,
* INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY,
* AND FITNESS FOR A PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP
* PRODUCTS, COMBINATION WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION.
* IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
* INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
* WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
* BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.
* TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL
* CLAIMS IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF
* FEES, IF ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
* MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE
* OF THESE TERMS.
*****************************************************************************/

/** @file pldm_config.h
 *  PLDM configuration header file
 */
/** @defgroup PLDM Configuration
 */

#ifndef PLDM_CONFIG_H
#define PLDM_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif


#define PLDM_DEVICE_DESCRIPTOR_OVERRIDE   0x1
#define PLDM_OVERRIDE_CAPABLITIES         0x1
#define PLDM_OVERRIDE_COMP_CLASSIFICATION 0x1
#define PLDM_DEVICE_IDENTIFIER_LENGTH     0xc8
#define PLDM_DESCRIPTOR_COUNT             0x10

#define PLDM_DESCRIPTOR_0 0x28537687
#define PLDM_DESCRIPTOR_4 0x54761786
#define PLDM_DESCRIPTOR_8 0x78764662
#define PLDM_DESCRIPTOR_12 0x39990007
#define PLDM_DESCRIPTOR_16 0x51002214
#define PLDM_DESCRIPTOR_20 0x25
#define PLDM_DESCRIPTOR_24 0x0
#define PLDM_DESCRIPTOR_28 0x0
#define PLDM_DESCRIPTOR_32 0x0
#define PLDM_DESCRIPTOR_36 0x0
#define PLDM_DESCRIPTOR_40 0x0
#define PLDM_DESCRIPTOR_44 0x0
#define PLDM_DESCRIPTOR_48 0x0
#define PLDM_DESCRIPTOR_52 0x0
#define PLDM_DESCRIPTOR_56 0x0
#define PLDM_DESCRIPTOR_60 0x0
#define PLDM_DESCRIPTOR_64 0x0
#define PLDM_DESCRIPTOR_68 0x0
#define PLDM_DESCRIPTOR_72 0x0
#define PLDM_DESCRIPTOR_76 0x0
#define PLDM_DESCRIPTOR_80 0x0
#define PLDM_DESCRIPTOR_84 0x0
#define PLDM_DESCRIPTOR_88 0x0
#define PLDM_DESCRIPTOR_92 0x0
#define PLDM_DESCRIPTOR_96 0x0
#define PLDM_DESCRIPTOR_100 0x0
#define PLDM_DESCRIPTOR_104 0x0
#define PLDM_DESCRIPTOR_108 0x0
#define PLDM_DESCRIPTOR_112 0x0
#define PLDM_DESCRIPTOR_116 0x0
#define PLDM_DESCRIPTOR_120 0x0
#define PLDM_DESCRIPTOR_124 0x0
#define PLDM_DESCRIPTOR_128 0x0
#define PLDM_DESCRIPTOR_132 0x0
#define PLDM_DESCRIPTOR_136 0x0
#define PLDM_DESCRIPTOR_140 0x0
#define PLDM_DESCRIPTOR_144 0x0
#define PLDM_DESCRIPTOR_148 0x0
#define PLDM_DESCRIPTOR_152 0x0
#define PLDM_DESCRIPTOR_156 0x0
#define PLDM_DESCRIPTOR_160 0x0
#define PLDM_DESCRIPTOR_164 0x0
#define PLDM_DESCRIPTOR_168 0x0
#define PLDM_DESCRIPTOR_172 0x0
#define PLDM_DESCRIPTOR_176 0x0
#define PLDM_DESCRIPTOR_180 0x0
#define PLDM_DESCRIPTOR_184 0x0
#define PLDM_DESCRIPTOR_188 0x0
#define PLDM_DESCRIPTOR_192 0x0
#define PLDM_DESCRIPTOR_196 0x0
#define GET_DESC(x)  PLDM_DESCRIPTOR_##x

#define PLDM_UPGRADE_CAPABLITIES          0x24

#define PLDM_COMP_CLASSIFICATION          0xc
#define PLDM_DEVICE_TID                   0x1

#define COMP_STRING_TYPE_SIZE ASCII_SIZE_VERSION_SIZE
#define UTF16_SIZE 2
#define ASCII_SIZE 40
#define UTF8 1
#define UTF16LE 2
#define UTF16BE 2
#define ONE_KB          1024
#define ASCII_SIZE_VERSION_SIZE 4

// string types
#define ASCII 0x01
#define UTF16  0X03

#define NO_OF_COMP_TBL 35
#define PLDM_DEFAULT_COMP_CLASSIFICATION 0x000A
#define PLDM_COMP_ACTIVATION_SUPPORTED 0x003A

#ifdef __cplusplus
}
#endif

#endif /* PLDM_CONFIG_H */

/**   @}
 */