
/*****************************************************************************
* Copyright (c) 2022 Microchip Technology Inc. and its subsidiaries.
* You may use this software and any derivatives exclusively with
* Microchip products.
* THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".
* NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE,
* INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY,
* AND FITNESS FOR A PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP
* PRODUCTS, COMBINATION WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION.
* IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
* INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
* WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
* BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.
* TO THE FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL
* CLAIMS IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF
* FEES, IF ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
* MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE
* OF THESE TERMS.
*****************************************************************************/

/** @file spdm_config.h
 *  SPDM configuration header file
 */
/** @defgroup SPDM Configuration
 */

#ifndef SPDM_CONFIG_H
#define SPDM_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif


#define SPDM_SLOT_CERT_CHAIN01 0x28
#define SPDM_SLOT_CERT_CHAIN23 0x88
#define SPDM_SLOT_CERT_CHAIN45 0x88
#define SPDM_SLOT_CERT_CHAIN67 0x88

#define SPDM_HEAD_POINTER_0 0x40
#define SPDM_HEAD_POINTER_1 0x40
#define SPDM_HEAD_POINTER_2 0x40
#define SPDM_HEAD_POINTER_3 0x40
#define SPDM_HEAD_POINTER_4 0x40
#define SPDM_HEAD_POINTER_5 0x40
#define SPDM_HEAD_POINTER_6 0x40
#define SPDM_HEAD_POINTER_7 0x40

#define TAIL_CERTIFICATE0123 0xffffffff
#define TAIL_CERTIFICATE4567 0xffffffff
#define TAIL_CERTIFICATE891011 0xffffffff
#define TAIL_CERTIFICATE12131415 0xffffffff
#define TAIL_CERTIFICATE16171819 0xffffffff
#define TAIL_CERTIFICATE20212223 0xffffffff
#define TAIL_CERTIFICATE24252627 0xffffffff
#define TAIL_CERTIFICATE28293031 0xffffffff
#define TAIL_CERTIFICATE32333435 0xffffffff
#define TAIL_CERTIFICATE36373839 0xffffffff
#define TAIL_CERTIFICATE40414243 0xffffffff
#define TAIL_CERTIFICATE44454647 0xffffffff
#define TAIL_CERTIFICATE48495051 0xffffffff
#define TAIL_CERTIFICATE52535455 0xffffffff
#define TAIL_CERTIFICATE56575859 0xffffffff
#define TAIL_CERTIFICATE60616263 0xffffffff

#ifdef __cplusplus
}
#endif

#endif /* SPDM_CONFIG_H */

/**   @}
 */